### ISSUE TITLE
Fix invariant violation error in ExplicitChecks

### ISSUE THREAD

**Issue by leuschel** [favu100/b2program#16]
make ExplicitChecks LANGUAGE=java DIRECTORY=benchmarks/model_checking/ProB/Other
java -jar B2Program-all-0.1.0-SNAPSHOT.jar -l java -mc true -f benchmarks/model_checking/ProB/Other/ExplicitChecks.mch
cp benchmarks/model_checking/ProB/Other/*.java .
javac -cp .:btypes.jar ExplicitChecks.java
java -cp .:btypes.jar ExplicitChecks mixed 1 false
INVARIANT VIOLATED
COUNTER EXAMPLE TRACE: 

_get_x: 0
Number of States: 2
Number of Transitions: 2

**Comment by favu100** [comment]
This problem also occurs for C++

**Comment by favu100** [comment]
This issue is solved now. It was caused by a wrong implementation of composition. 
In particular, the problem occurs when the relational image on a singleton set of a domain element is the empty set. The internal representation maps to the empty set due to performance reason. This means that the implementation of the equal operator differs from the equality of the underlying PersistentHashMap data structure


Nevertheless, the model's invariant is too complicated so that model checking finishes in reasonable time
